region = "us-east-1"
profile = "opsline-corp"

code_bucket = ""
instance_name_pattern = ""
# backup_interval = "24"
source_account = ""
# share_snapshots = "true"
# backup_schedule = "0 1 * * ? *"
# retention_days = "7"
# log_level = "ERROR"
# lambda_cw_log_retention = "7"
# source_region_override = "NO"
# delete_old_snapshots = "true"
# tagged_instance = "false"


# destination_account = "000000000000"
destination_region = ""
snapshot_pattern = ""
# kms_key_destination = "None"
# kms_key_source = "None"
# cross_account_copy = "true"